<?php
// lang/en.php

return [
    // General
    // ... (previous translations remain the same)
    // Property Interactions
    'invalid_rating_value_en_ar' => 'Invalid rating value. Please choose between 1 and 5.',
    'rating_submitted_successfully_en_ar' => 'Your rating has been submitted successfully.',
    'already_following_property_en_ar' => 'You are already following this property.',
    'property_followed_successfully_en_ar' => 'Property followed successfully.',
    'property_unfollowed_successfully_en_ar' => 'Property unfollowed successfully.',
    'not_following_property_en_ar' => 'You are not following this property.',
    'your_rating_en_ar' => 'Your Rating',
    'stars_en_ar' => 'Stars',
    'comment_en_ar' => 'Comment (Optional)',
    'select_rating_en_ar' => 'Select Rating',
    'to_rate_property_en_ar' => 'to rate this property.',
    'to_follow_property_en_ar' => 'to follow this property.',
    'average_rating_en_ar' => 'Average Rating',
    'default_inquiry_message_en_ar' => 'I am interested in this property: {property_title}. Please contact me.',
    'no_followed_properties_en_ar' => 'You are not currently following any properties.',
    'no_ratings_submitted_en_ar' => 'You have not submitted any ratings yet.',
    'view_property_en_ar' => 'View Property',
    'rated_on_en_ar' => 'Rated on',

    // General
    'site_name' => 'Manazel Real Estate',
    'toggle_navigation' => 'Toggle navigation',
    'home' => 'Home',
    'about_us' => 'About Us',
    'services' => 'Services',
    'listings' => 'Listings',
    'contact_us' => 'Contact Us',
    'login' => 'Login',
    'register' => 'Register',
    'logout' => 'Logout',
    'my_profile' => 'My Profile',
    'admin_panel' => 'Admin Panel',
    'search' => 'Search',
    'submit' => 'Submit',
    'read_more' => 'Read More',
    'language' => 'Language',
    'english' => 'English',
    'arabic' => 'Arabic',

    // Homepage
    'welcome_message' => 'Find Your Dream Home With Us',
    'featured_properties' => 'Featured Properties',
    'latest_news' => 'Latest News & Articles',
    'our_services_title' => 'Our Services',
    'testimonials_title' => 'What Our Clients Say',
    'consultation' => 'Consultation',
    'management' => 'Management',

    // Property
    'property_details' => 'Property Details',
    'price' => 'Price',
    'bedrooms' => 'Bedrooms',
    'bathrooms' => 'Bathrooms',
    'area_sqm' => 'Area (sqm)',
    'type' => 'Type',
    'status' => 'Status',
    'location' => 'Location',
    'view_details' => 'View Details',
    'rate_property' => 'Rate this Property',
    'follow_property' => 'Follow this Property',
    'unfollow_property' => 'Unfollow this Property',

    // Contact Form
    'contact_form_title' => 'Get In Touch',
    'your_name' => 'Your Name',
    'your_email' => 'Your Email',
    'subject' => 'Subject',
    'message' => 'Message',
    'send_message' => 'Send Message',
    'contact_info' => 'Contact Information',

    // Auth
    'username' => 'Username',
    'password' => 'Password',
    'confirm_password' => 'Confirm Password',
    'full_name' => 'Full Name',
    'email_address' => 'Email Address',
    'phone_number' => 'Phone Number',
    'already_have_account' => 'Already have an account? Login here.',
    'dont_have_account' => "Don't have an account? Register here.",
    'login_successful' => 'Login Successful!',
    'registration_successful' => 'Registration Successful!',
    'logout_successful' => 'You have been logged out.',
    'incorrect_login' => 'Incorrect username or password.',
    'login_now_prompt_en_ar' => 'You can now login with your credentials.',
    'optional_en_ar' => 'Optional',
    'or_email_en_ar' => 'or Email',

    // User Profile
    'edit_profile' => 'Edit Profile',
    'change_password' => 'Change Password',
    'current_password' => 'Current Password',
    'new_password' => 'New Password',
    'confirm_new_password' => 'Confirm New Password',
    'update_profile' => 'Update Profile',
    'profile_updated_successfully' => 'Profile updated successfully.',
    'password_changed_successfully' => 'Password changed successfully.',
    'followed_properties_en_ar' => 'Followed Properties',
    'my_ratings_en_ar' => 'My Ratings',
    'coming_soon_en_ar' => 'This feature is coming soon.',
    'password_min_length_en_ar' => 'Password must be at least 6 characters long.',
    'incorrect_current_password_en_ar' => 'Incorrect current password.',

    // Admin Panel
    'dashboard' => 'Dashboard',
    'manage_properties' => 'Manage Properties',
    'add_new_property' => 'Add New Property',
    'edit_property' => 'Edit Property',
    'delete_property' => 'Delete Property',
    'manage_users' => 'Manage Users',
    'property_title' => 'Property Title',
    'description' => 'Description',
    'property_type' => 'Property Type',
    'property_status' => 'Property Status',
    'address' => 'Address',
    'city' => 'City',
    'country' => 'Country',
    'main_image' => 'Main Image',
    'gallery_images' => 'Gallery Images',
    'add_image' => 'Add Image',
    'property_added_successfully' => 'Property added successfully.',
    'property_updated_successfully' => 'Property updated successfully.',
    'property_deleted_successfully' => 'Property deleted successfully.',

    // Errors & Messages
    'error_404_message' => 'Oops! The page you are looking for could not be found.',
    'error_generic_message' => 'An error occurred. Please try again later.',
    'fill_required_fields' => 'Please fill all required fields.',
    'passwords_do_not_match' => 'Passwords do not match.',
    'email_already_exists' => 'This email address is already registered.',
    'username_already_exists' => 'This username is already taken.',
    'invalid_email_format' => 'Invalid email format. Please enter a valid email address.',

    // Footer
    'copyright' => '&copy; {year} Manazel Real Estate. All Rights Reserved.',

    // About Us Page
    'about_us_intro_placeholder_p1_en_ar' => 'Manazel Real Estate is a premier real estate company dedicated to helping you find your perfect property. With years of experience and a commitment to excellence, we strive to provide the best service to our clients.',
    'our_mission_en_ar' => 'Our Mission',
    'our_mission_text_placeholder_en_ar' => 'Our mission is to simplify the property buying and selling process, making it transparent and stress-free for everyone involved. We leverage technology and market expertise to achieve the best outcomes.',
    'our_vision_en_ar' => 'Our Vision',
    'our_vision_text_placeholder_en_ar' => 'Our vision is to be the most trusted and respected real estate agency in the region, known for our integrity, professionalism, and client satisfaction.',
    'meet_our_team_en_ar' => 'Meet Our Team',

    // Services Page
    'services_intro_placeholder_en_ar' => 'At Manazel Real Estate, we offer a comprehensive suite of services to meet all your property needs. Our experienced team is dedicated to providing exceptional support and guidance throughout your real estate journey.',
    'service_sales_leasing_en_ar' => 'Sales & Leasing',
    'service_sales_leasing_desc_en_ar' => 'Whether you are looking to buy, sell, or lease a property, our expert agents are here to guide you through every step, ensuring a smooth and successful transaction.',
    'service_property_management_en_ar' => 'Property Management',
    'service_property_management_desc_en_ar' => 'We offer comprehensive property management services, taking care of everything from tenant screening and rent collection to maintenance and financial reporting.',
    'service_investment_consultancy_en_ar' => 'Investment Consultancy',
    'service_investment_consultancy_desc_en_ar' => 'Our investment consultancy services provide expert advice and market insights to help you make informed decisions and maximize your returns in the real estate market.',
    'service_valuation_en_ar' => 'Property Valuation',
    'service_valuation_desc_en_ar' => 'Accurate property valuation is crucial. Our certified valuers provide detailed and reliable valuation reports for various purposes.',
    'service_legal_assistance_en_ar' => 'Legal Assistance',
    'service_legal_assistance_desc_en_ar' => 'Navigating the legal aspects of real estate can be complex. We offer legal assistance to ensure all your transactions are compliant and secure.',
    'service_maintenance_en_ar' => 'Maintenance Services',
    'service_maintenance_desc_en_ar' => 'We provide reliable and timely maintenance services to keep your property in top condition, ensuring tenant satisfaction and preserving its value.',

    // Contact Page
    'contact_intro_placeholder_en_ar' => 'We would love to hear from you! Whether you have a question about our services, properties, or anything else, our team is ready to answer all your inquiries.',
    'send_us_a_message_en_ar' => 'Send Us a Message',
    'contact_address_placeholder_en_ar' => '123 Real Estate St, Property City, PC 45678',
    'contact_phone_placeholder_en_ar' => '+1 234 567 8900',
    'contact_email_placeholder_en_ar' => 'info@manazel.me',
    'working_hours_en_ar' => 'Working Hours',
    'contact_hours_placeholder_en_ar' => 'Mon - Fri: 9:00 AM - 6:00 PM<br>Sat: 10:00 AM - 4:00 PM<br>Sun: Closed',
    'message_sent_successfully' => 'Your message has been sent successfully! We will get back to you shortly.',

    // Listings Page
    'listings_intro_placeholder_en_ar' => 'Explore our wide range of properties. Use the filters below to find the one that suits your needs.',
    'search_keyword_placeholder_en_ar' => 'Keyword (e.g. villa, sea view)',
    'all_types_en_ar' => 'All Types',
    'villa_en_ar' => 'Villa',
    'apartment_en_ar' => 'Apartment',
    'house_en_ar' => 'House',
    'any_status_en_ar' => 'Any Status',
    'for_sale_en_ar' => 'For Sale',
    'for_rent_en_ar' => 'For Rent',
    'location_placeholder_en_ar' => 'Location (e.g. City, Region)',
    'previous_en_ar' => 'Previous',
    'next_en_ar' => 'Next',

    // Property Details Page
    'property_features_en_ar' => 'Property Features',
    'user_interactions_en_ar' => 'User Interactions',
    'submit_rating_en_ar' => 'Submit Rating',
    'login_required_en_ar' => 'Login Required',
    'follow_en_ar' => 'Follow',
    'unfollow_en_ar' => 'Unfollow',
    'contact_agent_en_ar' => 'Contact Agent',
    'send_inquiry_en_ar' => 'Send Inquiry',
];

